'use strict';
const { v4 } = require('uuid');
require('dotenv').config();

module.exports = {
    up: (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert(
            'TEAMS',
            [
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '두가티분당',
                    team_entry: 1,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '지벤&스핀휠',
                    team_entry: 2,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모토라드대구B',
                    team_entry: 3,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '대충탄다',
                    team_entry: 4,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '윤레이싱1',
                    team_entry: 5,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'M.B.R 1',
                    team_entry: 6,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '짠짜이',
                    team_entry: 7,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'FRracing1',
                    team_entry: 8,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'TAIWAN 초청',
                    team_entry: 9,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '꽃중년F4',
                    team_entry: 10,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'KKM금강',
                    team_entry: 11,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '프로젝트뮤',
                    team_entry: 12,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '동일이',
                    team_entry: 13,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'TAIWAN SINSHAN',
                    team_entry: 14,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'ADTBonami',
                    team_entry: 15,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'FRracing2',
                    team_entry: 16,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'VISION 봉재경',
                    team_entry: 17,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: "R'TEAMMBC",
                    team_entry: 18,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '필리핀 초청',
                    team_entry: 19,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모토라이드A',
                    team_entry: 20,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모토밸류',
                    team_entry: 21,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '베이비스텝 ',
                    team_entry: 22,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모토라이드C',
                    team_entry: 23,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '조선레이싱',
                    team_entry: 24,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '도미노피자 정관점_BG',
                    team_entry: 25,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'VISION.네아이엄빠',
                    team_entry: 26,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'REBS3',
                    team_entry: 27,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'Liqui Moly Racing Team 1',
                    team_entry: 28,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '일본팀 초청',
                    team_entry: 29,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'BTSracing',
                    team_entry: 30,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '76드래곤즈',
                    team_entry: 31,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'DMR#2',
                    team_entry: 32,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모토라드대구A',
                    team_entry: 33,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'REBS1',
                    team_entry: 34,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'Team Kawasaki',
                    team_entry: 35,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '제해욱',
                    team_entry: 36,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '서브로',
                    team_entry: 37,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '혼다레이싱대구',
                    team_entry: 38,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '말레이시아 초청',
                    team_entry: 39,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '레드블리츠',
                    team_entry: 40,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '윤레이싱2',
                    team_entry: 41,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '리페이바이크A',
                    team_entry: 42,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '리페어바이크B',
                    team_entry: 43,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모토그로우',
                    team_entry: 44,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '팀테크니션 가와사키',
                    team_entry: 45,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'TeamZero',
                    team_entry: 46,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'REBS2',
                    team_entry: 47,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'SRS',
                    team_entry: 48,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '홍콩 초청',
                    team_entry: 49,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'DMR#1',
                    team_entry: 50,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모토라이드B',
                    team_entry: 51,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모토라드제주',
                    team_entry: 52,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '오렌지홀릭',
                    team_entry: 53,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '팀제로나인',
                    team_entry: 54,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'MOTOMS',
                    team_entry: 55,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '크레이지게러지',
                    team_entry: 56,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '바스터즈',
                    team_entry: 57,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '태광모터스포츠팀A',
                    team_entry: 58,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '태광모터스포츠팀B',
                    team_entry: 59,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '태광모터스포츠팀C',
                    team_entry: 60,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'LIQUI MOLY RACING TEAM 2 ',
                    team_entry: 61,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '바이크09  ',
                    team_entry: 62,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모터싸다구A',
                    team_entry: 63,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모터싸다구B',
                    team_entry: 64,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '짤바이크1',
                    team_entry: 65,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '짤바이크2',
                    team_entry: 66,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'KSEF & 모토그레시브',
                    team_entry: 67,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모터플레이스A',
                    team_entry: 68,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모터플레이스B',
                    team_entry: 69,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '모터플레이스C',
                    team_entry: 70,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '신포모터스',
                    team_entry: 71,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '투휠',
                    team_entry: 72,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '창원GP모터스',
                    team_entry: 73,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'TeamMOS',
                    team_entry: 74,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '펀데이',
                    team_entry: 75,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '창원야마하',
                    team_entry: 76,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'TwoWheel',
                    team_entry: 77,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '존테스코리아',
                    team_entry: 78,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '구룡오토바이A',
                    team_entry: 79,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '구룡오토바이B',
                    team_entry: 80,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'TRP',
                    team_entry: 81,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: 'ZONTES DAEGU',
                    team_entry: 82,
                },
                {
                    team_uuid: v4(),
                    team_year: process.env.YEAR,
                    team_name: '엠레이싱',
                    team_entry: 83,
                },
            ],
            {}
        );
    },

    down: (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete('TEAMS', null, {
            cascade: true,
        });
    },
};
